version: "3"
services:
  server:
    image: tjperr/shoppingcart-server:latest
    environment:
      CART_DB_CONN_STR: 'admin:password@tcp(database:3306)/shoppingcart-db?tls=false&timeout=30s'
    ports:
      - "8080:8080"
    networks:
      - shoppingcart

  database:
    image: tjperr/shoppingcart-db:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    networks:
      shoppingcart:
        aliases:
         - database

networks:
  shoppingcart:
